### ISSUE TITLE
Revert OTEL collector builder installation to binary download

### ISSUE THREAD

**Issue by albertteoh** [jaegertracing/jaeger-otelcol#20]
[opentelemetry-collector-builder README instructions](https://github.com/observatorium/opentelemetry-collector-builder) are outdated and downloading the binary should be the right way to install it.

Related comment: https://github.com/jaegertracing/jaeger-otelcol/pull/18#issuecomment-757819212

**Comment by kevinearls** [comment]
I tried to work on this yesterday and ran into problems which I first thought were caused by https://github.com/observatorium/opentelemetry-collector-builder/pull/28

However, it turns out the real problem is https://github.com/observatorium/opentelemetry-collector-builder/issues/30  

In my case I think things appeared to work for me as I had an older version downloaded and the builds just continued using that.  If we are going to have the Makefile do a download we might need to check the version too.

**Comment by jpkrohling** [comment]
> go get github.com/observatorium/opentelemetry-collector-builder works for me and gives me version 0.4.0

If you run the builder's binary with `--help`, do you see the build tags properly set?

**Comment by kevinearls** [comment]
I get: 
```

opentelemetry-collector-builder --help
OpenTelemetry Collector distribution builder (dev)

Usage:
  opentelemetry-collector-builder [flags]

Flags:
      --config string            config file (default is $HOME/.otelcol-builder.yaml)
      --description string       A descriptive name for the OpenTelemetry Collector distribution (default "Custom OpenTelemetry Collector distribution")
      --go string                The Go binary to use during the compilation phase (default "/usr/bin/go")
  -h, --help                     help for opentelemetry-collector-builder
      --include-core             Whether the core components should be included in the distribution (default true)
      --module string            The Go module for the new distribution (default "github.com/jpkroehling/opentelemetry-collector-builder")
      --name string              The executable name for the OpenTelemetry Collector distribution (default "otelcol-custom")
      --otelcol-version string   Which version of OpenTelemetry Collector to use as base (default "0.18.0")
      --output-path string       Where to write the resulting files (default "/var/folders/c1/_dm_dl1d7953gtq8dmyfx9x80000gp/T/otelcol-distribution033054249")
      --version string           The version for the OpenTelemetry Collector distribution (default "1.0.0")
```

btw --version doesn't give the version?

**Comment by jpkrohling** [comment]
Good point, `--version` is to set which version of the otelcol to use. Would indeed have been better to use a different name for this property.
