### ISSUE TITLE
Update otelcol-builder binary on version mismatch

### ISSUE THREAD

**Issue by albertteoh** [jaegertracing/jaeger-otelcol#30]
Relates to: https://github.com/jaegertracing/jaeger-otelcol/issues/20#issuecomment-767456855

In the Makefile, we define: `OTELCOL_BUILDER_VERSION ?= 0.2.0`

If we upgrade this version, currently running `make build-agent` does not upgrade the otelcol-builder. Instead we need to delete the existing installed binary then run `make build-agent`.

We should update the Makefile or associated script to upgrade the otelcol-builder whenever there is a version mismatch between what's defined in the Makefile and the version of the otelcol-builder. It would rely on fixing the existing `--version` flag to print out the build version.

**Comment by jpkrohling** [comment]
I think a `make build-*` should always build a new binary, independent of the versions being used.

**Comment by albertteoh** [comment]
> I think a `make build-*` should always build a new binary, independent of the versions being used.

Currently, `make build-*` depends on the `otelcol-builder` target, which will install the otelcol-builder. So the suggestion here is that the `otelcol-builder` should respect the version set in the `Makefile`.

Are you suggesting that `make build-*` should not have a dependency on the `otelcol-builder` make target?

**Comment by jpkrohling** [comment]
Sorry, I misunderstood the issue here. I thought you were talking about the source that is generated by the builder, not the builder itself.
