### ISSUE TITLE
nit: Singular package name vs plural

### ISSUE THREAD

**Issue by albertteoh** [jaegertracing/jaeger-otelcol#34]
jaeger-otelcol uses the package names: `exporters`, `processors`, `receivers`.

https://github.com/open-telemetry/opentelemetry-collector uses the singular form: `exporter`, `processor`, `receiver`.

Should we maintain naming consistency with opentelemetry-collector or keep it as is?
I'm in favour of the former as it involves little effort now that may prevent future issues (thinking portability/maintainability).

**Comment by yurishkuro** [comment]
It is also Go convention to use singular package names
